### ISSUE TITLE
pcbre doesn't display images

### ISSUE THREAD

**Issue by trou** [davidcarne/pcbre#2]
After managing to install (see #1), pcbre starts but fails to display images, screen stays black.

The following backtrace may explain why : 
```python
During Shader Compilation:  ("Shader compile failure (0): b'0:1(3): preprocessor error: syntax error, unexpected HASH_TOKEN\\n'", [b'#version 330\n', b'', b'\nin vec2 pos;\n\nuniform sampler2D tex1;\nuniform vec4 color;\n//uniform float gamma;\n\n\nvoid main(void)\n{\n    float dist = texture2D(tex1, pos).r;\n    float d = dist - 0.75;\n\n    float aa = clamp(0.75*length( vec2( dFdx( d ), dFdy( d ))), 0.001, 1);\n\n\n    vec4 newcolor = color;\n    newcolor.a *= smoothstep(-aa, +aa, dist - 0.75);\n    gl_FragColor = newcolor;\n}\n'], GL_FRAGMENT_SHADER)
Traceback (most recent call last):
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/ui/boardviewwidget.py", line 315, in initializeGL
    self.gls.initializeGL()
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/ui/gl/glshared.py", line 21, in initializeGL
    self.text.initializeGL()
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/ui/gl/textrender.py", line 471, in initializeGL
    self.sdf_shader = self.gls.shader_cache.get("image_vert", "tex_frag")
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/ui/gl/shadercache.py", line 72, in get
    raise e
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/ui/gl/shadercache.py", line 67, in get
    frag = GLS.compileShader([frag_version, frag_prepend, frag1s], GL.GL_FRAGMENT_SHADER)
  File "/usr/lib/python3/dist-packages/OpenGL/GL/shaders.py", line 231, in compileShader
    shaderType,
RuntimeError: ("Shader compile failure (0): b'0:1(3): preprocessor error: syntax error, unexpected HASH_TOKEN\\n'", [b'#version 330\n', b'', b'\nin vec2 pos;\n\nuniform sampler2D tex1;\nuniform vec4 color;\n//uniform float gamma;\n\n\nvoid main(void)\n{\n    float dist = texture2D(tex1, pos).r;\n    float d = dist - 0.75;\n\n    float aa = clamp(0.75*length( vec2( dFdx( d ), dFdy( d ))), 0.001, 1);\n\n\n    vec4 newcolor = color;\n    newcolor.a *= smoothstep(-aa, +aa, dist - 0.75);\n    gl_FragColor = newcolor;\n}\n'], GL_FRAGMENT_SHADER)


```

**Comment by trou** [comment]
It was because `python3-opengl` from Debian doesn't seem to support shaders.
Using `pip install PyOpenGL-accelerate PyOpenGL` fixed it!

**Comment by trou** [comment]
Images are displayed when loading them, keypoints can be added but nothing is displayed in the main window.

**Comment by davidcarne** [comment]
Hi trou.  After adding images to the project, you need to associate them with PCB layers, so the SW knows what to draw. Do they show up if you add stackup layers via `edit->stackup`, and then associate the images with them using `edit->edit stackup/imagery pairing` ?

I know some documentation would probably be fantastic - I'm going to try and write some over the weekend.

**Comment by davidcarne** [comment]
Also - can you run `glxinfo | grep Core` and see if you have support for OpenGL 3.3 or later? You might need to upgrade mesa if you're getting shader compile errors. I use some OpenGL 3.2/3.3 features to make up for python's slowness at issuing draw calls.

**Comment by trou** [comment]
mesa should be ok : ̀OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.5.7`

I did :
 - add a layer
 - add images
 - associate them

but the main screen stays blank

**Comment by davidcarne** [comment]
Ok, thats definitely odd. The render paths should be the same for both the dialog as well as the main PCB view, and the view area defaults are sane-ish. Did you switch to a layer? (press '1' or '2', or select the layer in the RHS dialog?)

Can you send me the savefile and I'll take a look to see if I can figure out if its a transform or rendering issue?

**Comment by trou** [comment]
I definitely tried to switch to a layer. I can even draw on them but the image doesn't show up.

Unfortunately saving fails so I can't send you anything : 
```python
Saving to /home/raph/temp/test.pcbre
Traceback (most recent call last):
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/model/project.py", line 353, in save
    self.save_fd(f)
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/model/project.py", line 329, in save_fd
    message = self._serialize()
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/model/project.py", line 288, in _serialize
    project.imagery = self.imagery.serialize()
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/model/project.py", line 186, in serialize
    imagery.imagelayers[n] = i.serialize()
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/model/imagelayer.py", line 295, in serialize
    msg.transform.meta.rectTransformMeta = self.alignment.serialize()
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/model/imagelayer.py", line 137, in serialize
    msg.dims[n] = i
  File "capnp/lib/capnp.pyx", line 505, in capnp.lib.capnp._DynamicListBuilder.__setitem__ (capnp/lib/capnp.cpp:12910)
  File "capnp/lib/capnp.pyx", line 724, in capnp.lib.capnp._setDynamicField (capnp/lib/capnp.cpp:16065)
capnp.lib.capnp.KjException: src/capnp/dynamic.c++:1693: failed: Value type mismatch.
stack: 0x7fe082dfe0b9 0x7fe082e02c7d 0x7fe0832b79af 0x7fe0832ae78b 0x7fe0832b66c8 0x7fe083af5d87 0x7fe083af7f5a 0x50e37b 0x510fdc 0x510fdc 0x510fdc 0x510fdc 0x510fdc 0x5ab095 0x51163d 0x4c96b5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/ui/main_gui.py", line 91, in saveAs
    self.project.save(filename, update_path=True)
  File "/home/raph/tools/elec/pcbre/pysrc/pcbre/model/project.py", line 356, in save
    os.rename(bakname, path)
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/raph/temp/test.pcbre.bak' -> '/home/raph/temp/test.pcbre'
```

**Comment by davidcarne** [comment]
Ok, thats seriously weird. I'll need to setup a similar debian install and figure out whats going on.

**Comment by davidcarne** [comment]
Ok. I think I have a fix for the image rendering issue. If no dimensions were entered for the rectalign (just left with the placeholder values), the placeholder values would not be used for the final alignment calculation. This caused the rendered image to be smaller than a single pixel (100um x 100um max), and the save to fail.

Let me know if 989d7d1 resolves the issue.

**Comment by trou** [comment]
Great. Images are displayed in the main window.
